
name: Run Finanz-Agent

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # täglich 06:00 UTC

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run agent
        run: python finanzen_agent.py

      - name: Commit updated reports & workbook
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update reports & workbook"
          commit_user_name: "finanz-agent-bot"
          commit_user_email: "actions@github.com"
          file_pattern: |
            reports/**
            Budget.xlsx
            data/processed/**
